### ISSUE TITLE
[SYSTEM]: PF1E

### ISSUE THREAD

**Issue by winkles99** [ZotyDev/objects-interactions-fx#35] opened 2023-11-06 21:57 UTC
### Discord Username

sgtbun

### System

https://gitlab.com/foundryvtt_pathfinder1e/foundryvtt-pathfinder1

### Notes on the Support

I'm running 1E for a group of players for this first time, and this would be a great module to have! Thanks for all your hard work!

**Comment by ZotyDev** [comment] 2023-12-03 15:26
Duplicate of #13, please follow the other issue for updates on the support.

**Closed by ZotyDev** 2023-12-03 15:26 UTC
Labels: system
